// mtaa centre
export const SET_SELECTED_CENTER = "SET_SELECTED_CENTER";
export const FETCH_CENTERS_REQUEST = "FETCH_CENTERS_REQUEST";
export const FETCH_CENTERS_SUCCESS = "FETCH_CENTERS_SUCCESS";
export const FETCH_CENTERS_FAILURE = "FETCH_CENTERS_FAILURE";
export const SET_DISPLAYED = "SET_DISPLAYED";
export const SET_DISPLAY_UPDATE = "SET_DISPLAY_UPDATE";

export const FETCH_CENTER_BY_ID = "FETCH_CENTER_BY_ID";
export const ADD_CENTER = "ADD_CENTER";
export const UPDATE_CENTER = "UPDATE_CENTER";
export const DELETE_CENTER = "DELETE_CENTER";

export const FETCH_USER_REQUEST = "FETCH_USER_REQUEST";
export const FETCH_USER_SUCCESS = "FETCH_USER_SUCCESS";
export const FETCH_USER_FAILURE = "FETCH_USER_FAILURE";
export const REGISTER_USER = "REGISTER_USER";
export const LOGIN_USER = "LOGIN_USER";

// chtaktak
export const LOGIN = "LOGIN";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";

export const REGISTER = "REGISTER";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";

export const LOGOUT = "LOGOUT";
export const UPDATE_USER = "UPDATE_USER";

//mtaa vaccin
export const SET_SELECTED_VACCINE = "SET_SELECTED_VACCINE";
export const FETCH_VACCINES_REQUEST = "FETCH_VACCINES_REQUEST";
export const FETCH_VACCINES_SUCCESS = "FETCH_VACCINES_SUCCESS";
export const FETCH_VACCINES_FAILURE = "FETCH_VACCINES_FAILURE";

export const FETCH_VACCINE_BY_ID = "FETCH_VACCINE_BY_ID";
export const ADD_VACCINE = "ADD_VACCINE";
export const UPDATE_VACCINE = "UPDATE_VACCINE";
export const DELETE_VACCINE = "DELETE_VACCINE";
export const SET_DISPLAYED_VACCINE = "SET_DISPLAYED_VACCINE";
export const SET_DISPLAY_UPDATE_VACCINE = "SET_DISPLAY_UPDATE_VACCINE";
