//mtaa user
export const SET_SELECTED_USER = "SET_SELECTED_USER";
export const FETCH_USER_REQUEST = "FETCH_USER_REQUEST";
export const FETCH_USERS_SUCCESS = "FETCH_USERS_SUCCESS";
export const FETCH_USERS_FAILURE = "FETCH_USERS_FAILURE";
export const REGISTER_USER = "REGISTER_USER";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
//mtaa centre
export const SET_SELECTED_CENTER = "SET_SELECTED_CENTER";
export const FETCH_CENTERS_REQUEST = "FETCH_CENTERS_REQUEST";
export const FETCH_CENTERS_SUCCESS = "FETCH_CENTERS_SUCCESS";
export const FETCH_CENTERS_FAILURE = "FETCH_CENTERS_FAILURE";
export const SET_DISPLAYED = "SET_DISPLAYED";
export const SET_DISPLAY_UPDATE = "SET_DISPLAY_UPDATE";

export const FETCH_CENTER_BY_ID = "FETCH_CENTER_BY_ID";
export const ADD_CENTER = "ADD_CENTER";
export const UPDATE_CENTER = "UPDATE_CENTER";
export const DELETE_CENTER = "DELETE_CENTER";
export const ADD_VACCINE_TO_CENTER = "ADD_VACCINE_TO_CENTER";

//mtaa pharmacie
export const SET_SELECTED_PHARMACY = "SET_SELECTED_PHARMACY";
export const FETCH_PHARMACIES_REQUEST = "FETCH_PHARMACIES_REQUEST";
export const FETCH_PHARMACIES_SUCCESS = "FETCH_PHARMACIES_SUCCESS";
export const FETCH_PHARMACIES_FAILURE = "FETCH_PHARMACIES_FAILURE";

export const FETCH_PHARMACY_BY_ID = "FETCH_PHARMACY_BY_ID";
export const ADD_PHARMACY = "ADD_PHARMACY";
export const UPDATE_PHARMACY = "UPDATE_PHARMACY";
export const DELETE_PHARMACY = "DELETE_PHARMACY";

//mtaa vaccin
export const SET_SELECTED_VACCINE = "SET_SELECTED_VACCINE";
export const FETCH_VACCINES_REQUEST = "FETCH_VACCINES_REQUEST";
export const FETCH_VACCINES_SUCCESS = "FETCH_VACCINES_SUCCESS";
export const FETCH_VACCINES_FAILURE = "FETCH_VACCINES_FAILURE";

export const FETCH_VACCINE_BY_ID = "FETCH_VACCINE_BY_ID";
export const ADD_VACCINE = "ADD_VACCINE";
export const UPDATE_VACCINE = "UPDATE_VACCINE";
export const DELETE_VACCINE = "DELETE_VACCINE";
export const SET_DISPLAYED_VACCINE = "SET_DISPLAYED_VACCINE";
export const SET_DISPLAY_UPDATE_VACCINE = "SET_DISPLAY_UPDATE_VACCINE";
